apiVersion: apps/v1
kind: Deployment

metadata:
  name: pd-frontend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: pd-frontend

  template:
    metadata:
      labels:
        app: pd-frontend

    spec:
      containers:
      - name: pd-frontend

        image: plant-frontend:latest
        imagePullPolicy: Never

        ports:
        - containerPort: 80
